version: '3'

tasks:
  debug:
    method: checksum
    sources:
      - CMakeLists.txt
      - configuration/cmake/**/*.cmake
      - source/**/*.cpp
      - source/**/*.hpp
    generates:
      - build/debug/build.ninja
      - build/debug/baphomets_quest
      - build/debug/.task-build-debug.stamp
    cmds:
      - >-
        cmake -S . -B build/debug
        -G Ninja
        -DCMAKE_MAKE_PROGRAM=/opt/homebrew/bin/ninja
      - cmake --build build/debug --parallel
      - cmake -E touch build/debug/.task-build-debug.stamp

  release:
    method: checksum
    sources:
      - CMakeLists.txt
      - configuration/cmake/**/*.cmake
      - source/**/*.cpp
      - source/**/*.hpp
      - resources/**/*
    generates:
      - build/release/build.ninja
      - build/release/baphomets_quest
      - build/release/.task-build-release.stamp
    cmds:
      - >-
        cmake -S . -B build/release
        -G Ninja
        -DCMAKE_MAKE_PROGRAM=/opt/homebrew/bin/ninja
        -DCMAKE_BUILD_TYPE=Release
        -DBAPHOMETS_QUEST_RELEASE_OPTIMISATION=ON
      - >-
        cmake --build build/release
        --target bundle_resources
        --config Release
        --parallel
      - cmake -E touch build/release/.task-build-release.stamp

  clean:
    cmds:
      - rm -rf build
