version: '3'

tasks:
  debug:
    dir: ../..
    cmds:
      - >-
        cmake -S . -B build/debug
        -G Ninja
      - cmake --build build/debug --parallel

  release:
    dir: ../..
    cmds:
      - >-
        cmake -S . -B build/release
        -G Ninja
        -DCMAKE_BUILD_TYPE=Release
        -DBAPHOMETS_QUEST_RELEASE_OPTIMISATION=ON
      - >-
        cmake --build build/release
        --target bundle_resources
        --config Release
        --parallel

  clean:
    dir: ../..
    cmds:
      - rm -rf build
