game:
  target-frame-rate: 24

window:
  title: Baphomet's Quest
  width: 160
  height: 144

renderer:
  scale: 4
  clear-colour: '#20283dff'

audio:
  frequency: 44100
  channels: 2
  chunk-size: 2048
