name: Build Windows

on:
  workflow_dispatch:

  schedule:
    - cron: '0 6 * * 1'

permissions:
  actions: write
  contents: read

jobs:
  build:
    name: ${{ matrix.name }}
    uses: ./.github/workflows/build-platform.yaml

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x64
            artifact: baphomets-quest-windows-x64
            msystem: UCRT64
            package_prefix: mingw-w64-ucrt-x86_64
            runner: windows-latest
          - name: Windows x86
            artifact: baphomets-quest-windows-x86
            msystem: MINGW32
            package_prefix: mingw-w64-i686
            runner: windows-latest

    with:
      artifact: ${{ matrix.artifact }}
      msystem: ${{ matrix.msystem }}
      name: ${{ matrix.name }}
      package_prefix: ${{ matrix.package_prefix }}
      runner: ${{ matrix.runner }}
